/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosBibliotecario;
// Importamos el paquete de las herraminetas generales
import HerraminetasGenerales.*;
import HerraminetasGenerales.*;
// Insetamos el paquete Clases bibliotecario para direccionar a los diferentes Form
import ClasesDeBibliotecario.*;
// Importa el paquete de la base de datos para ser utilizado en el proyecto
import ConexionBDD.*;
// Importacines que se trabajara en el proyecto de la bdd
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Daniel_Márquez
 */
public class FormRegistracionPago extends javax.swing.JFrame {
     // Creamos una instancia de la clases de herramientas generales
    HerraminetasGenerlasApp HerrApp = new HerraminetasGenerlasApp();
    // Instacia para regresar Login 
    ClassRegresoLogin RegresarLogion = new ClassRegresoLogin();
    // Instanciamos la clases dirigir Form 
    classDirgirFormBibli Direccionar = new  classDirgirFormBibli();
    
     // Conexión de la base de datos
     conexionSQL cc = new conexionSQL();
       Connection con=cc.conexion();
    
    /**
     * Creates new form FormRegistracionPago
     */
    public FormRegistracionPago() {
        initComponents();
        HerrApp.IconoBibli(txtIconoBibli);
        HerrApp.ColorMenu(jpMenu);
        HerrApp.ColorBotones(btnPrestamos, btnRegistrar, btnDevolucion);
        HerrApp.ColorBotones(btnSolicitudes,BtnPagos, BtnPagos);
        HerrApp.IconoSalida(txtSalidad);
        HerrApp.ColorFondo(jpFondo);
        MostrarDatosPrestamos();
        MostrarDatosLibros();
        //Bloqueamos las cajas de textos
        txtIDMulta.setEnabled(false);
        txtNumeUser.setEnabled(false);
        txtReposicion.setEnabled(false);
        txtRegistroDineroBook.setEnabled(false);
        MostrarDatosPagoLibro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        txtIconoBibli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        BtnPagos = new javax.swing.JButton();
        btnSolicitudes = new javax.swing.JButton();
        txtSalidad = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDMulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegistrarDinero = new javax.swing.JTextField();
        btnActualizarMulta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBuscadorLibro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrarPagoLibro = new javax.swing.JButton();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtReposicion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRegistroDineroBook = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNumeUser = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCostoLibro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCantidadLibro = new javax.swing.JTextField();
        btnCalcularDinero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBuscadorCompras = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBuscadorMulta = new javax.swing.JTextField();
        btnCrearFactura = new javax.swing.JButton();
        txtNombreDELUSER = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIconoBibli.setText("ICONO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Pagos");

        btnRegistrar.setText("Registrar Libro");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnPrestamos.setText("Registro Prestamos");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });

        btnDevolucion.setText("Devolución Libro");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        BtnPagos.setText("Registración Multa o Pago");
        BtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagosActionPerformed(evt);
            }
        });

        btnSolicitudes.setText("Solicitudes Reservas");
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        txtSalidad.setText("Salidad");
        txtSalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalidadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtSalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtIconoBibli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtIconoBibli, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestamos)
                .addGap(4, 4, 4)
                .addComponent(btnDevolucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(txtSalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Realización de Pagos libro");

        jLabel6.setText("N° Registro:");

        jLabel7.setText("Registrar Dinero:");

        btnActualizarMulta.setText("Actualizar Multa");
        btnActualizarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMultaActionPerformed(evt);
            }
        });

        jLabel8.setText("Registros de Libros:");

        jLabel9.setText("Buscador:");

        txtBuscadorLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorLibroKeyReleased(evt);
            }
        });

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPrestamos);

        jLabel10.setText("Tipo Multa");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retraso de libro", "Daño", "Perdida de libro", "No Devuelto" }));

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLibros);

        jLabel11.setText("Estado:");

        btnRegistrarPagoLibro.setText("Registrar Pago Libro");
        btnRegistrarPagoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoLibroActionPerformed(evt);
            }
        });

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagado", "No Pagado" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Realización de Pagos de multas a los Estudiantes  y Docentes");

        jLabel5.setText("N° Usuario:");

        jLabel12.setText("Registrar Dinero:");

        txtRegistroDineroBook.setText("$");

        jLabel13.setText("Reposición De Libro:");

        jLabel14.setText("Cantidad:");

        txtCostoLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoLibroKeyTyped(evt);
            }
        });

        jLabel15.setText("Costo Libro:");

        txtCantidadLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadLibroKeyTyped(evt);
            }
        });

        btnCalcularDinero.setText("Calcular");
        btnCalcularDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDineroActionPerformed(evt);
            }
        });

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        jLabel16.setText("Registro de compras:");

        jLabel17.setText("Buscador:");

        txtBuscadorCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorComprasKeyReleased(evt);
            }
        });

        jLabel18.setText("Buscador:");

        txtBuscadorMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorMultaKeyReleased(evt);
            }
        });

        btnCrearFactura.setText("Crear Factura");
        btnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtRegistrarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIDMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(btnActualizarMulta)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreDELUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscadorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarPagoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegistroDineroBook, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(txtCantidadLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel15))
                            .addComponent(txtReposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCostoLibro)
                            .addComponent(btnCalcularDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(312, 312, 312)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscadorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtIDMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnActualizarMulta)
                                .addComponent(btnCrearFactura)
                                .addComponent(txtNombreDELUSER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txtBuscadorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(txtRegistrarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtBuscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtReposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularDinero))
                .addGap(18, 18, 18)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRegistroDineroBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtCostoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtCantidadLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPagoLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtBuscadorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoBibliotecario.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalidadMouseClicked
        RegresarLogion.RegresarLogin();// Regresamos al login
        this.dispose();// Cerramos la pantalla
    }//GEN-LAST:event_txtSalidadMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Direccionar.DireccionarRegistroLibro();
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        Direccionar.DireccionarPrestamos();
        this.dispose();
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        Direccionar.DireccionarDevolucion();
       this.dispose();
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
       Direccionar.DireccionarSolicitudes();
        this.dispose();
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void BtnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagosActionPerformed
       Direccionar.DireccionarPago();
        this.dispose();
    }//GEN-LAST:event_BtnPagosActionPerformed

    private void tblPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosMouseClicked
       int filasSeleccionada = tblPrestamos.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
       txtIDMulta.setText(tblPrestamos.getValueAt(filasSeleccionada, 0).toString());
       txtRegistrarDinero.setText(tblPrestamos.getValueAt(filasSeleccionada, 3).toString());
       cbxTipo.setSelectedItem(String.valueOf(tblPrestamos.getModel().getValueAt(filasSeleccionada,4)));
       cbxEstado.setSelectedItem(String.valueOf(tblPrestamos.getModel().getValueAt(filasSeleccionada,6)));
       txtNumeUser.setText(tblPrestamos.getValueAt(filasSeleccionada, 1).toString());
       txtNombreDELUSER.setText(tblPrestamos.getValueAt(filasSeleccionada, 2).toString());
    }//GEN-LAST:event_tblPrestamosMouseClicked

    private void tblLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibrosMouseClicked
        int filasSeleccionada = tblLibros.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
        txtReposicion.setText(tblLibros.getValueAt(filasSeleccionada, 1).toString());
        
    }//GEN-LAST:event_tblLibrosMouseClicked

    private void btnCalcularDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDineroActionPerformed

            if(txtCantidadLibro.getText().length()==0 || txtCostoLibro.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null, "No has ingresado la cantidad o el costo del libro verifique");
            }else{

        String can = txtCantidadLibro.getText();
        String Cos = txtCostoLibro.getText();
        int Mora = 2;
        int cantidad = Integer.parseInt(can);
        int costo = Integer.parseInt(Cos);
        int total = (cantidad * costo) + Mora;
         
        String resultado = Integer.toString(total);
        
        
        txtRegistroDineroBook.setText("$"+resultado);
            }
    }//GEN-LAST:event_btnCalcularDineroActionPerformed

    private void txtCantidadLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadLibroKeyTyped
char validar = evt.getKeyChar();
       
       if(Character.isLetter(validar))
       {
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(null, "Ingrese solo Numeros:");
       } 
    }//GEN-LAST:event_txtCantidadLibroKeyTyped

    private void txtCostoLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoLibroKeyTyped
      char validar = evt.getKeyChar();
       
       if(Character.isLetter(validar))
       {
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(null, "Ingrese solo Numeros:");
       } 
    }//GEN-LAST:event_txtCostoLibroKeyTyped

    private void btnActualizarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMultaActionPerformed
        ActualizarMulta();
        MostrarDatosPrestamos();
    }//GEN-LAST:event_btnActualizarMultaActionPerformed

    private void btnRegistrarPagoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoLibroActionPerformed
        RegistrarPagoLibro();
    }//GEN-LAST:event_btnRegistrarPagoLibroActionPerformed

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
        int filasSeleccionada = tblRegistros.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
        // Por medio cada columna trae los datos
        //txtIDpago.setText(tblRegistros.getValueAt(filasSeleccionada, 0).toString());

    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void txtBuscadorComprasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorComprasKeyReleased
          buscador(txtBuscadorCompras.getText());
    }//GEN-LAST:event_txtBuscadorComprasKeyReleased

    private void txtBuscadorMultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorMultaKeyReleased
        BuscadorPrestamos(txtBuscadorMulta.getText());
    }//GEN-LAST:event_txtBuscadorMultaKeyReleased

    private void txtBuscadorLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorLibroKeyReleased
         // TODO add your handling code here:
         BuscarLibros(txtBuscadorLibro.getText());
    }//GEN-LAST:event_txtBuscadorLibroKeyReleased

    private void btnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacturaActionPerformed
            factura fac = new factura();
            fac.setVisible(true);
            String nombre = txtNombreDELUSER.getText();
            fac.nombre.setText(nombre);
             Calendar cal = Calendar.getInstance();// Instanciamos a la clase de calendario;
            int año = cal.get(Calendar.YEAR); // Extraemos el año
            int mes = cal.get(Calendar.MONTH); // extraemos el mes
            int dia = cal.get(Calendar.DAY_OF_MONTH); // Extraemos  el dia 
            String Fecha = dia + "-" + mes + "-" + año; // Concatenamos la fecha del resgristo acutal.
            fac.fecha.setText(Fecha);
            String tipo = (String)cbxTipo.getSelectedItem();
            fac.Tipo.setText(tipo);
            String dinero = txtRegistrarDinero.getText();
            fac.dinero.setText(dinero);
            
            
    }//GEN-LAST:event_btnCrearFacturaActionPerformed
    
    
    
     // Metodo para mostrar los datos en Jtable de las reserva 
    public void MostrarDatosPrestamos()
    {
        String [] titulos = {"N° Registro","N° Usuario" ,"Nombre", "Multa","Tipo","Fecha" , "Estado", };
        String [] registros = new  String[7];
        
          
            
         DefaultTableModel modelo = new DefaultTableModel(null,titulos);
         String SQL =" select multa.IDregistro, user.IDusuario ,user.Nombre, multa.Multa, multa.Tipo,multa.Fecha,multa.Estado from registromulta as multa inner join usuarios as user on multa.IDusuario = user.IDusuario";
        
         try
         {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL);
               
             
               
               
           
            // Reccoremos la tabla para traer dicha información de cada empleado
            while (rs.next())
            {
             registros[0] = rs.getString("IDregistro");
             registros[1] = rs.getString("IDusuario");
             registros[2] = rs.getString("Nombre");   
             registros[3] = rs.getString("Multa");
             registros[4] = rs.getString("Tipo");
             registros[5] = rs.getString("Fecha");
             registros[6] = rs.getString("Estado");
             
             
                
             
             modelo.addRow(registros);                
            }
            
            tblPrestamos.setModel(modelo);  
         } catch(Exception e)
         {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
         }
    
    }//Fin del metodo de prestamos
    
    
    
    // Metodo para mostar los datos de los libros 
    
    // Metodo para mostrar los datos de los libros
    public void MostrarDatosLibros()
    {
        String [] titulos = {"N° Registro","Titulo","Categoria","Costo"};
        String [] registros = new  String[4];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro;";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Titulo");
             registros[2] = rs.getString("Categoria");
             registros[3] = rs.getString("Costo");
             
            
             modelo.addRow(registros);
            }
            tblLibros.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
        }
    }
    
    // Metodo para actualizar los datos de las multas de los usuarios
    
   public void ActualizarMulta()
   {
       if(txtIDMulta.getText().length()==0)
       {
           JOptionPane.showMessageDialog(null,"Debes Seleccionar al asurio que muestra en la tabla de multa");
       }
       else if (txtRegistrarDinero.getText().length()==0) 
       {
           JOptionPane.showMessageDialog(null,"Ingrese la cantidad de dinero");
       }else
       {
           try {
                // Por medio de la conuslta actulizamos el emppleado la cual en where le indicamos que se actualizar por medio del id
           String SQL = "update registromulta set Multa=?,Tipo=?,Estado=?  where IDregistro=?";
           
           int filasSeleccionada = tblPrestamos.getSelectedRow();
                    String dao = (String) tblPrestamos.getValueAt(filasSeleccionada, 0); // Fila seleccionada actulizamos la tabla
                    PreparedStatement pst=con.prepareStatement(SQL); // Preparamos la consulta
                    // Preparamos para insertar los datos correspondiente
                    pst.setString(1,txtRegistrarDinero.getText());
                    pst.setString(2,(String)cbxTipo.getSelectedItem());
                    pst.setString(3,(String)cbxEstado.getSelectedItem());
          // Guardamos los datos 
          pst.setString(4,dao);
          pst.execute();
          JOptionPane.showMessageDialog(null, "Registros Actualizado"); // Mostramos un mensaje
          txtRegistrarDinero.setText("");
          txtNumeUser.setText("");
                    
           } catch (Exception e) 
           {
               JOptionPane.showMessageDialog(null, "Error de Actualizar" + e );
           }
       
       }
   }
   
   // Metodo para registrar el pago del libro 
   
   public void RegistrarPagoLibro()
   {
       try 
       {
           //Variable que almacenara para insertar datos a la BD
            String SQL = "insert into pagolibro (IDusuario,PagoLibro,ReposiciónLibro,IDcompra,Cantidad ) values (?,?,?,?,?)"; 
            PreparedStatement pst=con.prepareStatement(SQL); // Prepara mos la consulta
           if (txtNumeUser.getText().length()==0)
           {
               JOptionPane.showMessageDialog(null,"No has selecciona al usuario de la tabla de las multas");
           }
           else if(txtReposicion.getText().length()==0)
           {
               JOptionPane.showMessageDialog(null,"No has selecciona el libro a reponer");
           }
           else if(txtRegistroDineroBook.getText().length()==0)
           {
               JOptionPane.showMessageDialog(null,"No has ingresado registro del costo ");
           }
           else
           {
               int espera = 0;
               // Si todo esta correcto mandaremos la información a cada columna
               pst.setString(1, txtNumeUser.getText());
               pst.setString(2, txtRegistroDineroBook.getText());
               pst.setString(3, txtReposicion.getText());
               pst.setInt(4, espera );
               pst.setString(5, txtCantidadLibro.getText());
               int n = pst.executeUpdate();
                        if(n > 0)
                        {
                             JOptionPane.showMessageDialog(null, "Registro con exito");
         // Mandamos a llamar el metodo para limpiar las cajas de textos
        txtNumeUser.setText("");
        txtRegistroDineroBook.setText("");
        txtReposicion.setText("");
        txtCantidadLibro.setText("");
        txtCostoLibro.setText("");
        MostrarDatosPagoLibro();
                            
                             
                        } // Fin del if
                
           }
           
       } catch (Exception e) 
       {
           JOptionPane.showMessageDialog(null, "Error Verifique:  " + e);  //Especificamos el error
       }
   }
    
    
      public  void MostrarDatosPagoLibro()
    {
        // Creamos la cabecera de la tabla.
        String[] titulos = {"N°","Reposición","Estado"};
        String[] registros = new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        //Realizamos la consulta para mostrar los datos    
        String SQL = "select pago.IDpago , user.Nombre , pago.PagoLibro , pago.ReposiciónLibro,pago.Cantidad , estado.Nombre as 'Estado'from pagolibro as pago inner join usuarios as user on user.IDusuario = pago.IDusuario left join est_compra as estado on pago.IDcompra = estado.IDcompra;";
        try 
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
             // Reccoremos la tabla para traer dicha información de cada empleado
             while(rs.next())
             {
               registros[0] = rs.getString("IDpago");
               registros[1] = rs.getString("ReposiciónLibro");
               registros[2] = rs.getString("Estado");
               modelo.addRow(registros);  
             }// Fin de while 
             tblRegistros.setModel(modelo);
             
            
        } catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Verificar el usuario 
        }

    }
    
      
       // Metodo para buscar 
    public void buscador(String valor)
    {
         // Creamos la cabecera de la tabla.
        String[] titulos = {"N°","Reposición","Estado"};
        String[] registros = new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        //Realizamos la consulta para mostrar los datos    
        String SQL = "select pago.IDpago , user.Nombre , pago.PagoLibro , pago.ReposiciónLibro , estado.Nombre as 'Estado'from pagolibro as pago inner join usuarios as user on user.IDusuario = pago.IDusuario left join est_compra as estado on pago.IDcompra = estado.IDcompra  where pago.ReposiciónLibro like '%"+valor+"%' or estado.Nombre like '%"+valor+"%'";
        
        try 
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            while(rs.next())
             {
               registros[0] = rs.getString("IDpago");
               registros[1] = rs.getString("ReposiciónLibro");
               registros[2] = rs.getString("Estado");

               modelo.addRow(registros);  
             }// Fin de while 
             tblRegistros.setModel(modelo);
            
        } catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null, "Error al mostrar datos Busqueda" + e.getMessage());   
        }
        
        
    }// Fin del Metodo de buscar
    
    
 //Buscador
    public void BuscadorPrestamos(String valor)
    {
        String [] titulos = {"N° Registro","N° Usuario" ,"Nombre", "Multa","Tipo","Fecha" , "Estado", };
        String [] registros = new  String[7];
        
          
            
         DefaultTableModel modelo = new DefaultTableModel(null,titulos);
         String SQL =" select multa.IDregistro, user.IDusuario ,user.Nombre, multa.Multa, multa.Tipo,multa.Fecha,multa.Estado from registromulta as multa inner join usuarios as user on multa.IDusuario = user.IDusuario where user.Nombre like '%"+valor+"%'";
        
         try
         {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL);
               
             
               
               
           
            // Reccoremos la tabla para traer dicha información de cada empleado
            while (rs.next())
            {
             registros[0] = rs.getString("IDregistro");
             registros[1] = rs.getString("IDusuario");
             registros[2] = rs.getString("Nombre");   
             registros[3] = rs.getString("Multa");
             registros[4] = rs.getString("Tipo");
             registros[5] = rs.getString("Fecha");
             registros[6] = rs.getString("Estado");
             
             
                
             
             modelo.addRow(registros);                
            }
            
            tblPrestamos.setModel(modelo);  
         } catch(Exception e)
         {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
         }
    
    }//Fin del metodo de prestamos
    
    
    
    // Metodo para buscar los libors
    public void BuscarLibros(String valor)
    {
        String [] titulos = {"N° Registro","Titulo","Categoria","Costo"};
        String [] registros = new  String[4];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro where Titulo like '%"+valor+"%'";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Titulo");
             registros[2] = rs.getString("Categoria");
             registros[3] = rs.getString("Costo");
             
            
             modelo.addRow(registros);
            }
            tblLibros.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistracionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistracionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistracionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistracionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistracionPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPagos;
    private javax.swing.JButton btnActualizarMulta;
    private javax.swing.JButton btnCalcularDinero;
    private javax.swing.JButton btnCrearFactura;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarPagoLibro;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtBuscadorCompras;
    private javax.swing.JTextField txtBuscadorLibro;
    private javax.swing.JTextField txtBuscadorMulta;
    private javax.swing.JTextField txtCantidadLibro;
    private javax.swing.JTextField txtCostoLibro;
    private javax.swing.JTextField txtIDMulta;
    private javax.swing.JLabel txtIconoBibli;
    private javax.swing.JTextField txtNombreDELUSER;
    private javax.swing.JTextField txtNumeUser;
    private javax.swing.JTextField txtRegistrarDinero;
    private javax.swing.JTextField txtRegistroDineroBook;
    private javax.swing.JTextField txtReposicion;
    private javax.swing.JLabel txtSalidad;
    // End of variables declaration//GEN-END:variables
}
