/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosBibliotecario;
// Importamos el paquete de las herraminetas generales
import HerraminetasGenerales.*;
// Insetamos el paquete Clases bibliotecario para direccionar a los diferentes Form
import ClasesDeBibliotecario.*;
// Importa el paquete de la base de datos para ser utilizado en el proyecto
import ConexionBDD.*;

// Importacines que se trabajara en el proyecto de la bdd
// Importamos otros paquetes que seran utilizado en la base de datos 
import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import java.text.DateFormat;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.regex.*;
//Importamos los paquetes del calendario 
import java.util.Date;

import java.text.DateFormat;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.view.save.JRPdfSaveContributor.*;
import net.sf.jasperreports.view.JRViewer.*;
import net.sf.jasperreports.view.save.JRMultipleSheetsXlsSaveContributor.*;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.export.SimplePdfExporterConfiguration;
import net.sf.jasperreports.view.JasperViewer;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfTable;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;

import java.awt.*;
import javax.swing.*;
        




/**
 *
 * @author Daniel_Márquez
 */
public class FormRegistrarLibro extends javax.swing.JFrame {
    // Creamos una instancia de la clases de herramientas generales
    HerraminetasGenerlasApp HerrApp = new HerraminetasGenerlasApp();
     // Instacia para regresar Login 
    ClassRegresoLogin RegresarLogion = new ClassRegresoLogin(); // Instacia para regresar Login 
     // Instanciamos la clases dirigir Form 
    classDirgirFormBibli Direccionar = new  classDirgirFormBibli();
    //Creamos la instancia herraminetas Bibliotecario
    HerramientasBibli OpcHerr = new HerramientasBibli();
    
     // Conexión de la base de datos
     conexionSQL cc = new conexionSQL();
       Connection con=cc.conexion();
    
    
    /**
     * Creates new form FormRegistrarLibro
     */
    public FormRegistrarLibro() {
        initComponents();
        HerrApp.IconoBibli(txtIconoBibli);
        HerrApp.ColorMenu(jpMenu);
        HerrApp.ColorBotones(btnPrestamos, btnRegistrar, btnDevolucion);
        HerrApp.ColorBotones(btnSolicitudes,BtnPagos, BtnPagos);
        HerrApp.IconoSalida(txtSalidad);
        HerrApp.ColorFondo(jpFondo);
        MostrarDatos(); // Mandamos a llamar el metodo para cargar los datos en la tabla que es extraido en BDD
        txtFecha.setEnabled(false);
        OpcHerr.DesactivarTextBox(txtCodigoLibro, txtlibro, cbxCategoria, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
        OpcHerr.DesactivarBotones(btnRegistrarLibro, btnActualizarBook, btnEliminarBook, btnBorrarCampos);
        txtIDLibro.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        txtIconoBibli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        BtnPagos = new javax.swing.JButton();
        btnSolicitudes = new javax.swing.JButton();
        txtSalidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoLibro = new javax.swing.JTextField();
        txtlibro = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnHabilitatarRegistro = new javax.swing.JButton();
        btnRegistrarLibro = new javax.swing.JButton();
        btnActualizarBook = new javax.swing.JButton();
        btnEliminarBook = new javax.swing.JButton();
        btnBorrarCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibro = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        txtPrestasmos = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        txtIDLibro = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIconoBibli.setText("ICONO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Libro");

        btnRegistrar.setText("Registrar Libro");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnPrestamos.setText("Registro Prestamos");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });

        btnDevolucion.setText("Devolución Libro");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        BtnPagos.setText("Registración Multa o Pago");
        BtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagosActionPerformed(evt);
            }
        });

        btnSolicitudes.setText("Solicitudes Reservas");
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        txtSalidad.setText("Salidad");
        txtSalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalidadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtSalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtIconoBibli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtIconoBibli, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestamos)
                .addGap(4, 4, 4)
                .addComponent(btnDevolucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoBibliotecario.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bienvenido: Aquí podras realizar el registros de los libros la cual podras  tambien de actualizar, eliminar y buscar");

        jLabel3.setText("Codigo Libro:");

        jLabel5.setText("Titulo Libro:");

        jLabel6.setText("Categoria:");

        jLabel7.setText("Autor:");

        txtAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAutorKeyTyped(evt);
            }
        });

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Fecha Ingreso:");

        jLabel10.setText("Dias Prestamos");

        jLabel11.setText("Costo:");

        btnHabilitatarRegistro.setText("Agregar un nuevo registro");
        btnHabilitatarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitatarRegistroActionPerformed(evt);
            }
        });

        btnRegistrarLibro.setText("Registrar");
        btnRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibroActionPerformed(evt);
            }
        });

        btnActualizarBook.setText("Actualizar");
        btnActualizarBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBookActionPerformed(evt);
            }
        });

        btnEliminarBook.setText("Eliminar");
        btnEliminarBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBookActionPerformed(evt);
            }
        });

        btnBorrarCampos.setText("Borrar Campos");
        btnBorrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCamposActionPerformed(evt);
            }
        });

        tblLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibro);

        jLabel12.setText("Registros de libros");

        jLabel13.setText("Buscador:");

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        txtPrestasmos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrestasmosKeyTyped(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtCosto.setText("$");
        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
        });

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemáticas", "Física", "Ciencia", "Lenguaje", "Programación", "Informaticas", "Redes", "Web", "estadísticas", "Historia de obras", "Diseño", "Literatura", "Obras", "Ciencia" }));

        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(btnHabilitatarRegistro)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel12)
                        .addGap(329, 329, 329)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3))
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpFondoLayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(txtCodigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtlibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbxCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(btnRegistrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnActualizarBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminarBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jpFondoLayout.createSequentialGroup()
                                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel10))
                                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jpFondoLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jpFondoLayout.createSequentialGroup()
                                                    .addGap(39, 39, 39)
                                                    .addComponent(txtPrestasmos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(jpFondoLayout.createSequentialGroup()
                                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9))
                                            .addGap(39, 39, 39)
                                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                .addComponent(txtFecha))))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnBorrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReporte))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabilitatarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrestasmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(20, 20, 20)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarBook)
                            .addComponent(btnRegistrarLibro)
                            .addComponent(btnEliminarBook)
                            .addComponent(btnBorrarCampos)
                            .addComponent(btnReporte))
                        .addGap(29, 29, 29)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalidadMouseClicked
         RegresarLogion.RegresarLogin();// Regresamos al login
        this.dispose();// Cerramos la pantalla
    }//GEN-LAST:event_txtSalidadMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       Direccionar.DireccionarRegistroLibro();
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
         Direccionar.DireccionarPrestamos();
        this.dispose();
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
       Direccionar.DireccionarDevolucion();
       this.dispose();
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
         Direccionar.DireccionarSolicitudes();
        this.dispose();
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void BtnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagosActionPerformed
        Direccionar.DireccionarPago();
        this.dispose();
    }//GEN-LAST:event_BtnPagosActionPerformed
    // Boton para registrar los libros 
    private void btnRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibroActionPerformed
       InsertarRegistrosLibro();
       MostrarDatos();
       
       
       
    }//GEN-LAST:event_btnRegistrarLibroActionPerformed

    private void btnBorrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCamposActionPerformed
       // Mandamos a llamar el metodo para limpiar las cajas de textos
        OpcHerr.LimpiartxtRegistroBook(txtCodigoLibro,txtlibro, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
    }//GEN-LAST:event_btnBorrarCamposActionPerformed

    // Evento para seleccionar la fila seleciionada y mostrarlo en los textbox
    private void tblLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibroMouseClicked
       int filasSeleccionada = tblLibro.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
    
       // Por medio cada columna trae los datos
       txtIDLibro.setText(tblLibro.getValueAt(filasSeleccionada,0).toString());
       txtCodigoLibro.setText(tblLibro.getValueAt(filasSeleccionada,1).toString());        
       txtlibro.setText(tblLibro.getValueAt(filasSeleccionada,2).toString());
       cbxCategoria.setSelectedItem(String.valueOf(tblLibro.getModel().getValueAt(filasSeleccionada,3)));
       txtAutor.setText(tblLibro.getValueAt(filasSeleccionada,4).toString());
       txtCantidad.setText(tblLibro.getValueAt(filasSeleccionada,5).toString());
       txtFecha.setText(tblLibro.getValueAt(filasSeleccionada,6).toString());
       txtPrestasmos.setText(tblLibro.getValueAt(filasSeleccionada,7).toString());
       txtCosto.setText(tblLibro.getValueAt(filasSeleccionada,8).toString());
       
       // Activamos los campos y los botones
      OpcHerr.ActivarTextBox(txtCodigoLibro, txtlibro, cbxCategoria, txtAutor, txtCantidad, txtPrestasmos, txtCosto); // Metodos que llamamos
      OpcHerr.HabilitarDosBotones(btnActualizarBook,btnEliminarBook); // Metodos que llamamos
      OpcHerr.DesactivarDosBotones(btnRegistrarLibro,btnBorrarCampos);
       
       
    }//GEN-LAST:event_tblLibroMouseClicked
  //Evento para validar el ingreso de numeros
    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
      char validar = evt.getKeyChar();
       
       if(Character.isLetter(validar))
       {
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(null, "Ingrese solo Numeros:");
       }
    }//GEN-LAST:event_txtCantidadKeyTyped
//Evento para validar el ingreso de numeros
    private void txtPrestasmosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrestasmosKeyTyped
        char validar = evt.getKeyChar();
       
       if(Character.isLetter(validar))
       {
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(null, "Ingrese solo Numeros:");
       } 
    }//GEN-LAST:event_txtPrestasmosKeyTyped

    private void txtAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorKeyTyped
      char validar = evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo Letras");
        }
    }//GEN-LAST:event_txtAutorKeyTyped

    private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoKeyTyped
   // Boton para eliminar el registro de un libro
    private void btnEliminarBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBookActionPerformed
      
         int resp=JOptionPane.showConfirmDialog(null,"Seguro que desea eliminar el libro");
      if (JOptionPane.OK_OPTION == resp){
       EliminarRegistro();
       MostrarDatos();
       OpcHerr.DesactivarTextBox(txtCodigoLibro, txtlibro, cbxCategoria, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
       OpcHerr.DesactivarBotones(btnRegistrarLibro, btnActualizarBook, btnEliminarBook, btnBorrarCampos);
    }
        
    }//GEN-LAST:event_btnEliminarBookActionPerformed

    private void btnActualizarBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBookActionPerformed
          int resp=JOptionPane.showConfirmDialog(null,"Seguro que desea actualizar el libro");
      if (JOptionPane.OK_OPTION == resp){
       ActualizarDatos();
       MostrarDatos();
       OpcHerr.DesactivarTextBox(txtCodigoLibro, txtlibro, cbxCategoria, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
       OpcHerr.DesactivarBotones(btnRegistrarLibro, btnActualizarBook, btnEliminarBook, btnBorrarCampos);
    }
    }//GEN-LAST:event_btnActualizarBookActionPerformed
   // Boton para activar los campos y los botnes
    private void btnHabilitatarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitatarRegistroActionPerformed
      OpcHerr.ActivarTextBox(txtCodigoLibro, txtlibro, cbxCategoria, txtAutor, txtCantidad, txtPrestasmos, txtCosto); // Metodos que llamamos
      OpcHerr.HabilitarDosBotones(btnRegistrarLibro, btnBorrarCampos); // Metodos que llamamos para activar los botones
      OpcHerr.DesactivarDosBotones(btnEliminarBook, btnActualizarBook); // Desactivar 
     // Mandamos a llamar el metodo para limpiar las cajas de textos
        OpcHerr.LimpiartxtRegistroBook(txtCodigoLibro,txtlibro, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
    txtFecha.setText("");// Limpiamos fecha
    }//GEN-LAST:event_btnHabilitatarRegistroActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
       buscar(txtBuscador.getText());// Metodo para buscar funciona por codigo,titulo,categoria
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
       
   Document documento = new Document();
   
        try 
        {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento,new FileOutputStream(ruta + "/Desktop/Reporte_Libros.pdf"));
             Paragraph parrafo = new Paragraph();
             parrafo.setAlignment(Paragraph.ALIGN_CENTER);
             parrafo.add("Formato creado por Geekipedia de Daniel Márquez \n\n");
             parrafo.setFont(FontFactory.getFont("Tahoma",18,Font.BOLD,BaseColor.DARK_GRAY));
             parrafo.add("Registros de libros \n\n");
             
         
            
            documento.open();
            
            documento.add(parrafo);
            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("N°");
            tabla.addCell("Codigo");
            tabla.addCell("Titulo");
            tabla.addCell("Categoria");
            tabla.addCell("Autor");
            
            
            
            try {
                 Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bibli","root","");
                PreparedStatement pst = cn.prepareStatement("select * from libro");
                ResultSet rs = pst.executeQuery();
                
                if(rs.next())
                {
                    do
                    {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                    }while(rs.next());
                    documento.add(tabla);
                }
                
                
            } catch (DocumentException | SQLException e) 
            {
                JOptionPane.showMessageDialog(null, "Error de conexión" + e);
            }
            
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte Generado");
            
            
            // Fin del otra cahe
           
                
                
                
        }// fin del primer cahct    
            catch (DocumentException | HeadlessException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error de conexión" + e);
            }
            
            
       
      
      
     
     
        
    }//GEN-LAST:event_btnReporteActionPerformed

     // Metodo para mostrar los datos de los libros
    public void MostrarDatos()
    {
        String [] titulos = {"ID Libro","Codigo","Titulo","Categoria","Autor","Cantidad","Fecha Ingreso" ,"Dias Prestamos" ,"Costo"};
        String [] registros = new  String[9];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro;";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Codigo");
             registros[2] = rs.getString("Titulo");
             registros[3] = rs.getString("Categoria");
             registros[4] = rs.getString("Autor");
             registros[5] = rs.getString("Cantidad");
             registros[6] = rs.getString("FechaIngreso");
             registros[7] = rs.getString("DiasPrestamos");
             registros[8] = rs.getString("Costo");
             modelo.addRow(registros);
            }
            tblLibro.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
       
        }
        
        
        
    }
    
    //Metodo para insertar los libros
    public void InsertarRegistrosLibro()
    {
         
        try 
        {
            //Variable que almacenara para insertar datos a la BD
            String SQL = "insert into libro (Codigo,Titulo,Categoria,Autor,Cantidad,FechaIngreso,DiasPrestamos,Costo) values (?,?,?,?,?,?,?,?)"; 
            Calendar cal = Calendar.getInstance();// Instanciamos a la clase de calendario;
            int año = cal.get(Calendar.YEAR); // Extraemos el año
            int mes = cal.get(Calendar.MONTH); // extraemos el mes
            int dia = cal.get(Calendar.DAY_OF_MONTH); // Extraemos  el dia 
            String Fecha = dia + "-" + mes + "-" + año; // Concatenamos la fecha del resgristo acutal.
            
            // Validaciones 
            boolean status = OpcHerr.ValidarCodigoBook(txtCodigoLibro.getText());
            boolean status2 = OpcHerr.ValidarEntradaCosto(txtCosto.getText());
           
            
            
            PreparedStatement pst=con.prepareStatement(SQL); // Prepara mos la consulta
            if(txtCodigoLibro.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del codigo libro");
            }
            else if(!status)
            {
              JOptionPane.showMessageDialog(null,"No has ingresado el formato correcto del codigo del libro: AAA000");   
            }
            else if(txtlibro.getText().length()==0)
            {
                 JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del Titulo del libro ");
            }
            else if(txtAutor.getText().length()==0)
            {
              JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del autor");  
            }
            else if(txtCantidad.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto de cantidad");   
            }
            else if(txtCosto.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del costo");   
            }
            else if(!status2)
            {
               JOptionPane.showMessageDialog(null,"No has ingresado el formato correcto del ingreso de costo: $00.00 O $00");    
            }
            else 
            {
                 // Si todo esta correcto mandaremos la información a cada columna
                pst.setString(1, txtCodigoLibro.getText());
                pst.setString(2,txtlibro.getText());
                pst.setString(3,(String)cbxCategoria.getSelectedItem());
                pst.setString(4,txtAutor.getText());
                pst.setString(5,txtCantidad.getText());
                pst.setString(6,Fecha);
                pst.setString(7,txtPrestasmos.getText());
                pst.setString(8,txtCosto.getText());
                int n = pst.executeUpdate();
                        if(n > 0)
                        {
                             JOptionPane.showMessageDialog(null, "Registro con exito");
         // Mandamos a llamar el metodo para limpiar las cajas de textos
        OpcHerr.LimpiartxtRegistroBook(txtCodigoLibro,txtlibro, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
                            
                             
                        } // Fin del if
                        
                
                
            }
            
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error Verifique:  " + e);  //Especificamos el error
        }
    }// Fin del metodo de insetar datos de los libros.
    
    // Metodo para eliminar un registro
    
   public void EliminarRegistro()
   {
       String IDlibro = txtIDLibro.getText();
       
       try 
       {
           String SQL = "delete from libro where IDlibro = '"+IDlibro+"'"; // La consutla que eliminara el campo
         
           Statement st = con.createStatement();
            int n = st.executeUpdate(SQL); // Insertamos la consulta
            // Realiuza el cambio de la consulta
            if(n>=0)
            {
                JOptionPane.showMessageDialog(null,"Registros eliminado");
        // Mandamos a llamar el metodo para limpiar las cajas de textos
        OpcHerr.LimpiartxtRegistroBook(txtCodigoLibro,txtlibro, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
        txtIDLibro.setText("");
        txtFecha.setText("");
               
                
            }
           
           
       } catch (Exception e) 
       {
           JOptionPane.showMessageDialog(null, "Error al eliminar Registros"+e.getMessage()); // Mostrar el error
       }
   
   }// Fin del metodo de elimar registro
   
   
   // Metodo para Actualizar los datos de los libros
   public void ActualizarDatos()
   {
        // Validaciones 
            boolean status = OpcHerr.ValidarCodigoBook(txtCodigoLibro.getText());
            boolean status2 = OpcHerr.ValidarEntradaCosto(txtCosto.getText());
            
             if(txtCodigoLibro.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del codigo libro");
            }
            else if(!status)
            {
              JOptionPane.showMessageDialog(null,"No has ingresado el formato correcto del codigo del libro: AAA000");   
            }
            else if(txtlibro.getText().length()==0)
            {
                 JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del Titulo del libro ");
            }
            else if(txtAutor.getText().length()==0)
            {
              JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del autor");  
            }
            else if(txtCantidad.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto de cantidad");   
            }
            else if(txtCosto.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null,"No has ingresado ningun dato en la caja de texto del costo");   
            }
            else if(!status2)
            {
               JOptionPane.showMessageDialog(null,"No has ingresado el formato correcto del ingreso de costo: $00.00 O $00");    
            }
            else
            {
                try 
                {
                    // Por medio de la conuslta actulizamos el emppleado la cual en where le indicamos que se actualizar por medio del id
                    String SQL = "update libro set IDlibro=?,Codigo=?,Titulo=?,Categoria=?,Autor=?,Cantidad=?,DiasPrestamos=?,Costo=? where IDlibro=?";
                    int filasSeleccionada = tblLibro.getSelectedRow();
                    String dao = (String) tblLibro.getValueAt(filasSeleccionada, 0); // Fila seleccionada actulizamos la tabla
                    PreparedStatement pst=con.prepareStatement(SQL); // Preparamos la consulta
                    // Preparamos para insertar los datos correspondiente
                    pst.setString(1,txtIDLibro.getText());
                    pst.setString(2,txtCodigoLibro.getText());
                    pst.setString(3,txtlibro.getText());
                    pst.setString(4,(String)cbxCategoria.getSelectedItem());
                    pst.setString(5,txtAutor.getText());
                    pst.setString(6,txtCantidad.getText());
                    pst.setString(7,txtPrestasmos.getText());
                    pst.setString(8,txtCosto.getText());
          
          // Guardamos los datos 
          pst.setString(9,dao);
          pst.execute();
          JOptionPane.showMessageDialog(null, "Registros Actualizado"); // Mostramos un mensaje
          // Mandamos a llamar el metodo para limpiar las cajas de textos
        OpcHerr.LimpiartxtRegistroBook(txtCodigoLibro,txtlibro, txtAutor, txtCantidad, txtPrestasmos, txtCosto);
        txtIDLibro.setText("");
        txtFecha.setText("");
          
                    
                    
                    
                    
                } catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(null, "Error de Actualizar" +e );
                }
            } // Fin de else 
       
       
       
   } // Fin del METODO PARA ACTUALIZAR EL REGISTROS
   
   
   //Metodo para el buscador
   
   public void buscar(String valor)
   {
     
       String [] titulos = {"ID Libro","Codigo","Titulo","Categoria","Autor","Cantidad","Fecha Ingreso" ,"Dias Prestamos" ,"Costo"};
        String [] registros = new  String[9];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro where Titulo like '%"+valor+"%' or Categoria like '%"+valor+"%' or Codigo like '%"+valor+"%' ";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Codigo");
             registros[2] = rs.getString("Titulo");
             registros[3] = rs.getString("Categoria");
             registros[4] = rs.getString("Autor");
             registros[5] = rs.getString("Cantidad");
             registros[6] = rs.getString("FechaIngreso");
             registros[7] = rs.getString("DiasPrestamos");
             registros[8] = rs.getString("Costo");
             modelo.addRow(registros);
            }
            tblLibro.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
       
        }
       
   }
   
   
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPagos;
    private javax.swing.JButton btnActualizarBook;
    private javax.swing.JButton btnBorrarCampos;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnEliminarBook;
    private javax.swing.JButton btnHabilitatarRegistro;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarLibro;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JTable tblLibro;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoLibro;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIDLibro;
    private javax.swing.JLabel txtIconoBibli;
    private javax.swing.JTextField txtPrestasmos;
    private javax.swing.JLabel txtSalidad;
    private javax.swing.JTextField txtlibro;
    // End of variables declaration//GEN-END:variables
}
