/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosBibliotecario;
// Importamos el paquete de las herraminetas generales
import HerraminetasGenerales.*;
// Insetamos el paquete Clases bibliotecario para direccionar a los diferentes Form
import ClasesDeBibliotecario.*;
// Importa el paquete de la base de datos para ser utilizado en el proyecto
import ConexionBDD.*;

// Importacines que se trabajara en el proyecto de la bdd
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel_Márquez
 */
public class FormRegisroPrestamos extends javax.swing.JFrame {
    // Creamos una instancia de la clases de herramientas generales
    HerraminetasGenerlasApp HerrApp = new HerraminetasGenerlasApp();
     // Instacia para regresar Login 
    ClassRegresoLogin RegresarLogion = new ClassRegresoLogin();
     // Instanciamos la clases dirigir Form 
    classDirgirFormBibli Direccionar = new  classDirgirFormBibli();
    
     // Conexión de la base de datos
     conexionSQL cc = new conexionSQL();
       Connection con=cc.conexion();

    /**
     * Creates new form FormRegisroPrestamos
     */
    public FormRegisroPrestamos() {
        initComponents();
        HerrApp.IconoBibli(txtIconoBibli);
        HerrApp.ColorMenu(jpMenu);
        HerrApp.ColorBotones(btnPrestamos, btnRegistrar, btnDevolucion);
        HerrApp.ColorBotones(btnSolicitudes,BtnPagos, BtnPagos);
        HerrApp.IconoSalida(txtSalidad);
        HerrApp.ColorFondo(jpFondo);
        MostrarDatos();//Mostramos los datos de los libros
        MostrarDatosUser(); // Mostramos los datos de los usuarios
        txtIDUsuario.setEnabled(false);// Desactivamosla caja de texto del usuario.
        txtIDLibro.setEnabled(false);//Desactivamos la caja de texto del libro.
        txtVerifcarCantida.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        txtIconoBibli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        BtnPagos = new javax.swing.JButton();
        btnSolicitudes = new javax.swing.JButton();
        txtSalidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdtEntrega = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jdtDevolucion = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        btnRegistrarReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBuscadorUser = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBuscardorLibro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIDLibro = new javax.swing.JTextField();
        txtVerifcarCantida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIconoBibli.setText("ICONO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Prestamo");

        btnRegistrar.setText("Registrar Libro");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnPrestamos.setText("Registro Prestamos");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });

        btnDevolucion.setText("Devolución Libro");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        BtnPagos.setText("Registración Multa o Pago");
        BtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPagosActionPerformed(evt);
            }
        });

        btnSolicitudes.setText("Solicitudes Reservas");
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        txtSalidad.setText("Salidad");
        txtSalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalidadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtSalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtIconoBibli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtIconoBibli, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestamos)
                .addGap(4, 4, 4)
                .addComponent(btnDevolucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(txtSalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoBibliotecario.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Aquí podras realizar los prestamos de los libros para los usuarios");

        jLabel4.setText("N° Usuario:");

        jLabel5.setText("N° Libro");

        jLabel6.setText("Fechas Entrega:");

        jLabel7.setText("Fechas Devolución");

        jLabel8.setText("Estado Libro:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestado", "Reservado" }));
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });

        btnRegistrarReserva.setText("Registrar");
        btnRegistrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarReservaActionPerformed(evt);
            }
        });

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibros);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuarios);

        jLabel9.setText("Registro de Alumnos y Docentes");

        jLabel10.setText("Buscador:");

        txtBuscadorUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorUserKeyReleased(evt);
            }
        });

        jLabel11.setText("Registros de libros:");

        jLabel12.setText("Buscador:");

        txtBuscardorLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscardorLibroKeyReleased(evt);
            }
        });

        jLabel16.setText("Cantidad");

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDUsuario)
                            .addComponent(jcbEstado, 0, 150, Short.MAX_VALUE)
                            .addComponent(txtIDLibro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdtEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jdtDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad)))
                    .addComponent(btnRegistrarReserva))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(241, 241, 241)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscadorUser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jpFondoLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(txtBuscardorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtVerifcarCantida, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVerifcarCantida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jdtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addComponent(txtIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrarReserva)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtBuscadorUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(txtBuscardorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(jdtDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalidadMouseClicked
       RegresarLogion.RegresarLogin();// Regresamos al login
        this.dispose();// Cerramos la pantalla
    }//GEN-LAST:event_txtSalidadMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Direccionar.DireccionarRegistroLibro();
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        Direccionar.DireccionarPrestamos();
        this.dispose();
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        Direccionar.DireccionarDevolucion();
       this.dispose();
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
        Direccionar.DireccionarSolicitudes();
        this.dispose();
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void BtnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPagosActionPerformed
        Direccionar.DireccionarPago();
        this.dispose();
    }//GEN-LAST:event_BtnPagosActionPerformed

    private void btnRegistrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarReservaActionPerformed

        String ncantidades = txtVerifcarCantida.getText();
        if(ncantidades.equals("0"))
        {
          JOptionPane.showMessageDialog(null,"No hay libros por el momento.");  
        }else{


        if(txtIDUsuario.getText().length()==0)
          {
              JOptionPane.showMessageDialog(null,"Seleccione en la tabla de usuarios para extraer el N° Registro"); 
          }
          else if(txtIDLibro.getText().length()==0)
          {
              JOptionPane.showMessageDialog(null,"Seleccione en la tabla de libro para extraer el N° Registro");   
          }
          else if(jdtEntrega.getDate()==null)
          {
              JOptionPane.showMessageDialog(null,"Ingrese la fecha de entrega");   
          }
          else if(jdtDevolucion.getDate()==null)
          {
              JOptionPane.showMessageDialog(null,"Ingrese la fecha de devolución");   
          }
          else if(txtCantidad.getText().length()==0)
          {
              JOptionPane.showMessageDialog(null,"No has ingresado la cantidad de libro solicitado");   
          }
          else if(jdtEntrega.getDate()==null)
          {
               JOptionPane.showMessageDialog(null,"No has ingresado la fecha de entrada");
          }
          else if(jdtDevolucion.getDate()==null)
          {
             JOptionPane.showMessageDialog(null,"No has ingresado la fecha devolución"); 
          }
          else
          {
             ActualizarInventario();
             MostrarDatos();  
          }
        }
       
    }//GEN-LAST:event_btnRegistrarReservaActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
    int filasSeleccionada = tblUsuarios.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
    // Por medio cada columna trae los datos
    txtIDUsuario.setText(tblUsuarios.getValueAt(filasSeleccionada, 0).toString());
   
    
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void tblLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibrosMouseClicked
       int filasSeleccionada = tblLibros.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
         // Por medio cada columna trae los datos
         txtIDLibro.setText(tblLibros.getValueAt(filasSeleccionada, 0).toString());
         txtVerifcarCantida.setText(tblLibros.getValueAt(filasSeleccionada, 3).toString());
    }//GEN-LAST:event_tblLibrosMouseClicked

    private void txtBuscadorUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorUserKeyReleased
       //Metodo que llamamos para buscar al usuario
       BuscarUser(txtBuscadorUser.getText());
       
    }//GEN-LAST:event_txtBuscadorUserKeyReleased

    private void txtBuscardorLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscardorLibroKeyReleased
       //metodos que llamamos para buscar un libro
        BuscarLibro(txtBuscardorLibro.getText());
    }//GEN-LAST:event_txtBuscardorLibroKeyReleased

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoActionPerformed

    
     // Metodo para mostrar los datos de los libros
    public void MostrarDatos()
    {
        String [] titulos = {"N° Registro","Titulo","Categoria","Cantidad","Dias Prestamos"};
        String [] registros = new  String[5];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro;";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Titulo");
             registros[2] = rs.getString("Categoria");
             registros[3] = rs.getString("Cantidad");
             registros[4] = rs.getString("DiasPrestamos");
             modelo.addRow(registros);
            }
            tblLibros.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
        }
        
        
        
    }
    
    // Metodo para mostrar los datos del estudiantes para registrarlo en la base de datos.
    
    // Metodo para mostrar los datos en Jtable de los usuarios creados.
    public void MostrarDatosUser()
    {
        String [] titulos = {"ID Usuario", "Carnet", "Nombre","Cargo" , "Estado"};
        String [] registros = new  String[5];
        
         DefaultTableModel modelo = new DefaultTableModel(null,titulos);
         String SQL = "select user.IDusuario,user.Carnet,user.Nombre,rol.Nombre AS 'Cargo', estado.Nombre AS 'Estado' from usuarios as user inner join roles as rol on user.IDroles = rol.IDroles  LEFT JOIN servicio estado on  user.IDservicio = estado.IDservicio where user.IDroles= 2 or user.IDroles= 3";
        
         try
         {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL);
           
            // Reccoremos la tabla para traer dicha información de cada empleado
            while (rs.next())
            {
             registros[0] = rs.getString("IDusuario");
             registros[1] = rs.getString("Carnet");   
             registros[2] = rs.getString("Nombre");
             registros[3] = rs.getString("Cargo");
             registros[4] = rs.getString("Estado"); 
             modelo.addRow(registros);                
            }
            tblUsuarios.setModel(modelo);  
         } catch(Exception e)
         {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
         }
    
    }
    
    
    // Metodo para registrar el prestamo}
    
 public void InsertarRegistro()
 {
     try 
     {
          //Variable que almacenara para insertar datos a la BD
          String SQL = "insert into prestamo (IDusuario,IDlibro,FechaEntrega,FechaDevolucion,EstadoLibro,Cantidad,Hora,renovaciones) values (?,?,?,?,?,?,?,?)"; 
          PreparedStatement pst=con.prepareStatement(SQL); // Prepara mos la consulta
          int año = jdtEntrega.getCalendar().get(Calendar.YEAR);
          int mes = jdtEntrega.getCalendar().get(Calendar.MARCH);
          int dia = jdtEntrega.getCalendar().get(Calendar.DAY_OF_MONTH);
          String Entrega =  dia+"-"+mes+"-"+año;
          
          int año2 = jdtDevolucion.getCalendar().get(Calendar.YEAR);
          int mes2 = jdtDevolucion.getCalendar().get(Calendar.MARCH);
          int dia2= jdtDevolucion.getCalendar().get(Calendar.DAY_OF_MONTH);
          String Devolucion = dia2+"-"+mes2+"-"+año2;
          
           //Hora de registro
            Calendar calendario = Calendar.getInstance();
            int hora, minutos, segundos;
            hora =calendario.get(Calendar.HOUR_OF_DAY);
            minutos = calendario.get(Calendar.MINUTE);
            segundos = calendario.get(Calendar.SECOND);
            String  HoraRegistro = hora + ":" + minutos + ":" + segundos; // Extraemos la hora de registro
          
          String NumeroRenovacion="0";
          
          
          
         
             // Si todo esta correcto mandaremos la información a cada columna
            pst.setString(1, txtIDUsuario.getText());
            pst.setString(2, txtIDLibro.getText());
            pst.setString(3,Entrega);
            pst.setString(4,Devolucion);
            pst.setString(5,(String)jcbEstado.getSelectedItem());
            pst.setString(6,txtCantidad.getText());
            pst.setString(7,HoraRegistro);
            pst.setString(8,NumeroRenovacion);
            
            int n = pst.executeUpdate();
            if(n > 0)
            {
              JOptionPane.showMessageDialog(null, "Registro con exito");
              txtIDUsuario.setText("");
              txtIDLibro.setText("");
              txtCantidad.setText("");
            
          }
     } 
     catch (Exception e) 
     {
        JOptionPane.showMessageDialog(null, "Error Verifique:  " + e);  
     }
 }// Fin del METODO PARA INSERTAR PRESTAMOS DE LOS LIBROS
    
    
 
 //Metodo para actualizar el inventario()
 
  public void ActualizarInventario()
    {
        String Cantidad = txtCantidad.getText();
        String IDLibro = txtIDLibro.getText();
        try
        {
          String SQL = "UPDATE libro SET Cantidad = Cantidad - '"+Cantidad+"' WHERE IDlibro = '"+IDLibro+"'";   
           Statement st = con.createStatement();
           int n = st.executeUpdate(SQL); // Insertamos la consulta
           // Realiuza el cambio de la consulta
             
         
        if(n>=0)
            {
                JOptionPane.showMessageDialog(null,"Inventario Actualizado");
                InsertarRegistro();// Metodo que llamamos para insertar los datos a la BDD
            }
           
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error al eliminar Registros"+e.getMessage()); // Mostrar el error
        }
      
    }
    
    // Buscador de usuario
    public void BuscarUser(String valor)
    {  
        
        
        String [] titulos = {"ID Usuario", "Carnet", "Nombre","Cargo" , "Estado"};
        String [] registros = new  String[5];
        
         DefaultTableModel modelo = new DefaultTableModel(null,titulos);
         String SQL = "select user.IDusuario,user.Carnet,user.Nombre,rol.Nombre AS 'Cargo', estado.Nombre AS 'Estado' from usuarios as user inner join roles as rol on user.IDroles = rol.IDroles  LEFT JOIN servicio estado on  user.IDservicio = estado.IDservicio where user.Carnet like '%"+valor+"%' or user.Nombre like '%"+valor+"%'";
        
         try
         {
             if (txtBuscadorUser.getText().length()==0){
                 MostrarDatosUser();
             }else{
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL);
           
            // Reccoremos la tabla para traer dicha información de cada empleado
            while (rs.next())
            {
             registros[0] = rs.getString("IDusuario");
             registros[1] = rs.getString("Carnet");   
             registros[2] = rs.getString("Nombre");
             registros[3] = rs.getString("Cargo");
             registros[4] = rs.getString("Estado"); 
             modelo.addRow(registros);                
            }
            tblUsuarios.setModel(modelo);
             }
         } catch(Exception e)
         {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
         }
    
        
    }
    
    // Metodo para buscar un libro
    public void BuscarLibro(String valor)
    {
        String [] titulos = {"N° Registro","Titulo","Categoria","Cantidad","Dias Prestamos"};
        String [] registros = new  String[5];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro where Titulo like '%"+valor+"%'";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Titulo");
             registros[2] = rs.getString("Categoria");
             registros[3] = rs.getString("Cantidad");
             registros[4] = rs.getString("DiasPrestamos");
             modelo.addRow(registros);
            }
            tblLibros.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
        }
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegisroPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegisroPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegisroPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegisroPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisroPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPagos;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarReserva;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbEstado;
    private com.toedter.calendar.JDateChooser jdtDevolucion;
    private com.toedter.calendar.JDateChooser jdtEntrega;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscadorUser;
    private javax.swing.JTextField txtBuscardorLibro;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIDLibro;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JLabel txtIconoBibli;
    private javax.swing.JLabel txtSalidad;
    private javax.swing.JTextField txtVerifcarCantida;
    // End of variables declaration//GEN-END:variables
}
