/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosAdministrador;
// Importamos el paquete de las herramientas generales
import HerraminetasGenerales.*;

// Importacines que se trabajara en el proyecto de la bdd
import ClasesDeAdministrador.*;
// Importamos el paquete para clases login par mostra el nombre de user
import ClasesLogin.*;

// importamos la conexión con la base de datos 
import ConexionBDD.*;

// Importamos otros paquetes que seran utilizado en la base de datos 
import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.regex.*;



/**
 *
 * @author Daniel_Márquez
 */
public class FormReposicionLibro extends javax.swing.JFrame {
    // Instanciamos a la clases  Herramientas Generales
    HerraminetasGenerlasApp HerrOpc = new HerraminetasGenerlasApp();
    // Instacia para regresar Login 
    ClassRegresoLogin RegresarLogion = new ClassRegresoLogin();
    // Instanciamos a la clase direccionar a los formularios
    classDirigirForm Direccionar = new classDirigirForm();
     // instanciamos a la clases para  utilizar opciones generales del administrador
    HerraminetasAdmin OpcAdmin = new HerraminetasAdmin();
     // Instanciamos a la clases metodosLogin
    MetodosLogin user = new MetodosLogin();
    
    ResultSet llenarCombox; // Llenar el combox que sera utilizado anajo del codigo
      
    //Instanciamos la clases de la conexión de la base de datos
    conexionSQL cc = new conexionSQL();
    Connection con=cc.conexion();
    
    
    
     
    
    
    /**
     * Creates new form FormReposicionLibro
     */
    public FormReposicionLibro() {
        initComponents();
        // Agregamos los componentes
        HerrOpc.ColorBotones(btnCrearuser, btnVerLibros, btnReposicionLibro );
        HerrOpc.ColorMenu(jpMenu);
        HerrOpc.Icono(txtIconoAdmin);
        HerrOpc.IconoSalida(txtSalida);
        HerrOpc.ColorFondo(jpFondo);
        
        MostrarDatos();// Mostramos los datos de los registro de los pagos de los libros
        txtIDpago.setEnabled(false); // Desactivamos la caja de texto.
        lblUsuario.setText(user.NombreUser);// madanmos a llamar el nombre usuario logeado
        txtIDpago.setVisible(false);
        
        // Metodo para cargar los datos en e combox para estados de la compra
         LlenarEstadoCombox();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        txtIconoAdmin = new javax.swing.JLabel();
        btnCrearuser = new javax.swing.JButton();
        btnVerLibros = new javax.swing.JButton();
        btnReposicionLibro = new javax.swing.JButton();
        txtSalida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        txtIDpago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnEnviarEstado = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIconoAdmin.setText("ICONO");

        btnCrearuser.setText("Crear Usuarios");
        btnCrearuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearuserActionPerformed(evt);
            }
        });

        btnVerLibros.setText("Ver Registros Libro");
        btnVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLibrosActionPerformed(evt);
            }
        });

        btnReposicionLibro.setText("Reposición de Libro");
        btnReposicionLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReposicionLibroActionPerformed(evt);
            }
        });

        txtSalida.setText("Salida");
        txtSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalidaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvendio:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reposición de libro");

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("jLabel5");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVerLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addComponent(btnReposicionLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtIconoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtIconoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(btnCrearuser)
                .addGap(18, 18, 18)
                .addComponent(btnVerLibros)
                .addGap(18, 18, 18)
                .addComponent(btnReposicionLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Bienvenido: Aquí podras ver el registro de reposición de libro. La cual te podras encargar  en comprar libro y avisarle");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("al bibliotecario si se ha comprado,rechazado o en espera.");

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        jLabel6.setText("Buscador:");

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        txtIDpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDpagoActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado Compra:");

        btnEnviarEstado.setText("Enviar Datos");
        btnEnviarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEstadoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Registro");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel9.setText("Si la compra ya esta realizado y el bibliotecario");

        jLabel10.setText("ya registro el nuevo libro. puede eliminar el registro del pedido.");

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtIDpago, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(211, 211, 211)
                                        .addComponent(btnEliminar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                                        .addComponent(btnEnviarEstado)
                                        .addGap(229, 229, 229)))
                                .addGap(182, 182, 182))))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtIDpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnviarEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/para pricipiantes.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReposicionLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReposicionLibroActionPerformed
        Direccionar.DirigirResposicionLibro(); // Mostramos la interzas
        this.dispose();// Cerramos la ventana
    }//GEN-LAST:event_btnReposicionLibroActionPerformed

    private void btnCrearuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearuserActionPerformed
        Direccionar.DirigirCrearUser(); // Mostamos la interzas
        this.dispose();//Cerramos la ventana
    }//GEN-LAST:event_btnCrearuserActionPerformed

    private void btnVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLibrosActionPerformed
        Direccionar.DirigirVerInfoLibro();// Mostramos la interzas
        this.dispose(); // Cerramos la ventana
    }//GEN-LAST:event_btnVerLibrosActionPerformed

    private void txtSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalidaMouseClicked
        RegresarLogion.RegresarLogin();// Regresamos al login
        this.dispose();// Cerramos la pantalla
    }//GEN-LAST:event_txtSalidaMouseClicked

    private void txtIDpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDpagoActionPerformed

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
         int filasSeleccionada = tblRegistros.rowAtPoint(evt.getPoint()); //Evento para seleccionar la fila seleccionada
        // Por medio cada columna trae los datos
         txtIDpago.setText(tblRegistros.getValueAt(filasSeleccionada, 0).toString());
         
    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void btnEnviarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEstadoActionPerformed
       CambiarEstado();// LLamos al meto para actualizar el estado
    }//GEN-LAST:event_btnEnviarEstadoActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscador(txtBuscador.getText());
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     int resp=JOptionPane.showConfirmDialog(null,"Seguro que desea eliminar al usuario");
      if (JOptionPane.OK_OPTION == resp){
       EliminarRegistro();
       MostrarDatos();
    }
      
    }//GEN-LAST:event_btnEliminarActionPerformed

    ///////////////////////////////////////////////////////////////////////////
    //////             METODO PARA MOSTRAR LOS DATOS              ///////////// 
    ///////////////////////////////////////////////////////////////////////////
    
    public  void MostrarDatos()
    {
        // Creamos la cabecera de la tabla.
        String[] titulos = {"N°","Nombre","Pago","Reposición","Cantidad","Estado"};
        String[] registros = new String[6];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        //Realizamos la consulta para mostrar los datos    
        String SQL = "select pago.IDpago , user.Nombre , pago.PagoLibro , pago.ReposiciónLibro,pago.Cantidad , estado.Nombre as 'Estado'from pagolibro as pago inner join usuarios as user on user.IDusuario = pago.IDusuario left join est_compra as estado on pago.IDcompra = estado.IDcompra;";
        try 
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
             // Reccoremos la tabla para traer dicha información de cada empleado
             while(rs.next())
             {
               registros[0] = rs.getString("IDpago");
               registros[1] = rs.getString("Nombre");
               registros[2] = rs.getString("PagoLibro");
               registros[3] = rs.getString("ReposiciónLibro");
               registros[4] = rs.getString("Cantidad");
               registros[5] = rs.getString("Estado");
               modelo.addRow(registros);  
             }// Fin de while 
             tblRegistros.setModel(modelo);
             
            
        } catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Verificar el usuario 
        }

    }
    
    ///////////////////////////////////////////////////////////////////////////
    //////             Cambiar el estado de la comprar             ///////////// 
    ///////////////////////////////////////////////////////////////////////////
    
    public void CambiarEstado()
    {
    
        try 
        {
            if(txtIDpago.getText().length()==0)
            { 
                JOptionPane.showMessageDialog(null,"Debes Seleccionar un registro de tu tabla");
                
            }else
            {
 
            String SQL = "update pagolibro set IDcompra = ?  where IDpago = ?";
            int filasSeleccionada = tblRegistros.getSelectedRow();
            String dao = (String) tblRegistros.getValueAt(filasSeleccionada, 0); // Fila seleccionada actulizamos la tabla
            PreparedStatement pst=con.prepareStatement(SQL); // Preparamos la consulta
             // Preparamos para insertar los datos correspondiente 
             pst.setInt(1,cbxEstado.getSelectedIndex());
             // Guardamos los datos 
             pst.setString(2,dao);
             pst.execute();
            JOptionPane.showMessageDialog(null, "Registros Actualizado"); // Mostramos un mensjae que se guardar
            MostrarDatos(); // Recargamos la tabla
            txtIDpago.setText(""); // Limpiamos la caja de texto
            }
            
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error de Actualizar" +e );
        }
        
    }
    
   ///////////////////////////////////////////////////////////////////////////
   //////             Buscador                                  ///////////// 
   ///////////////////////////////////////////////////////////////////////////
   
    // Metodo para buscar 
    public void buscador(String valor)
    {
        // Creamos la cabecera de la tabla.
        String[] titulos = {"N°","Nombre","Pago","Reposición","Estado"};
        String[] registros = new String[5];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        //Realizamos la consulta para mostrar los datos    
        String SQL = "select pago.IDpago , user.Nombre , pago.PagoLibro , pago.ReposiciónLibro , estado.Nombre as 'Estado'from pagolibro as pago inner join usuarios as user on user.IDusuario = pago.IDusuario left join est_compra as estado on pago.IDcompra = estado.IDcompra  where pago.ReposiciónLibro like '%"+valor+"%' or estado.Nombre like '%"+valor+"%'";
        
        try 
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            while(rs.next())
             {
               registros[0] = rs.getString("IDpago");
               registros[1] = rs.getString("Nombre");
               registros[2] = rs.getString("PagoLibro");
               registros[3] = rs.getString("ReposiciónLibro");
               registros[4] = rs.getString("Estado");
               modelo.addRow(registros);  
             }// Fin de while 
             tblRegistros.setModel(modelo);
            
        } catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null, "Error al mostrar datos Busqueda" + e.getMessage());   
        }
        
        
    }// Fin del Metodo de buscar
    
    // Metodo para elimar el registro de pedido
   public void EliminarRegistro()
   {
       String IDRegistro = txtIDpago.getText();
       
       try 
       {
        String SQL = "delete from pagolibro where IDpago = '"+IDRegistro+"'";
        Statement st = con.createStatement();
            int n = st.executeUpdate(SQL); // Insertamos la consulta
            // Realiuza el cambio de la consulta
              if(n>=0)
            {
                JOptionPane.showMessageDialog(null,"Registros eliminado");
                 txtIDpago.setText(""); // Limpiamos la caja de texto                
            }
        
           
       } catch (Exception e) 
       {
            JOptionPane.showMessageDialog(null, "Error al eliminar Registros"+e.getMessage()); // Mostrar el error
       }
       
   }
    
    // Metodo para llenar el combo dl estado 
   public void LlenarEstadoCombox()
   {
       try {
            String SQL = "select * from est_compra ";
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while(rs.next())
            {
                LlenarComboEstCompra cbx = new LlenarComboEstCompra();
                cbx.setIDestaCompra(rs.getInt("IDcompra"));
                cbx.setNombreEstaCompra(rs.getString("Nombre"));
                cbxEstado.addItem(cbx.toString());
            }
           
       } catch (Exception e)
       {
           JOptionPane.showMessageDialog(null,"Error: Al Cargar los ComboBox de estado"+e);
       }
       
       
   } 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReposicionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReposicionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReposicionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReposicionLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReposicionLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrearuser;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviarEstado;
    public javax.swing.JButton btnReposicionLibro;
    public javax.swing.JButton btnVerLibros;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtIDpago;
    private javax.swing.JLabel txtIconoAdmin;
    public javax.swing.JLabel txtSalida;
    // End of variables declaration//GEN-END:variables
}
