/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosAdministrador;
// Importamos el paquete de las herramientas generales
import HerraminetasGenerales.*;
// Importamos el paquete para dirrecionar a los diferentes formularios
import ConexionBDD.*;
// Importacines que se trabajara en el proyecto de la bdd
import ClasesDeAdministrador.*;
// Importamos el paquete para clases login par mostra el nombre de user
import ClasesLogin.*;
// Importacines que se trabajara en el proyecto de la bdd
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel_Márquez
 */
public class FormVerLibros extends javax.swing.JFrame {

   // Instanciamos a la clases  Herramientas Generales
    HerraminetasGenerlasApp HerrOpc = new HerraminetasGenerlasApp();
    // Instacia para regresar Login 
    ClassRegresoLogin RegresarLogion = new ClassRegresoLogin();
    // Instanciamos a la clases para direccionar a la ventas
    classDirigirForm Direccionar = new classDirigirForm();
    // Instanciamos a la clases metodosLogin
    MetodosLogin user = new MetodosLogin();
     // Conexión de la base de datos
     conexionSQL cc = new conexionSQL();
       Connection con=cc.conexion();
    
    /**
     * Creates new form FormVerLibros
     */
    public FormVerLibros() {
        initComponents();
        // Agregamos los componentes
        HerrOpc.ColorBotones(btnCrearuser3, btnVerLibros3, btnReposicionLibro3 );
        HerrOpc.ColorMenu(jpMenu3);
        HerrOpc.Icono(txtIconoAdmin3);
        HerrOpc.IconoSalida(txtSalida3);
        HerrOpc.ColorFondo(jpFondo);   
        MostrarDatos();
       lblUsuario.setText(user.NombreUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu3 = new javax.swing.JPanel();
        txtIconoAdmin3 = new javax.swing.JLabel();
        btnCrearuser3 = new javax.swing.JButton();
        btnVerLibros3 = new javax.swing.JButton();
        btnReposicionLibro3 = new javax.swing.JButton();
        txtSalida3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIconoAdmin3.setText("ICONO");

        btnCrearuser3.setText("Crear Usuarios");
        btnCrearuser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearuser3ActionPerformed(evt);
            }
        });

        btnVerLibros3.setText("Ver Registros Libro");
        btnVerLibros3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLibros3ActionPerformed(evt);
            }
        });

        btnReposicionLibro3.setText("Reposición de Libro");
        btnReposicionLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReposicionLibro3ActionPerformed(evt);
            }
        });

        txtSalida3.setText("Salida");
        txtSalida3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalida3MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bienvendio:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ver Informe Libro");

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("jLabel5");

        javax.swing.GroupLayout jpMenu3Layout = new javax.swing.GroupLayout(jpMenu3);
        jpMenu3.setLayout(jpMenu3Layout);
        jpMenu3Layout.setHorizontalGroup(
            jpMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearuser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVerLibros3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addComponent(btnReposicionLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenu3Layout.createSequentialGroup()
                .addGroup(jpMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenu3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtIconoAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenu3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMenu3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsuario))
                    .addGroup(jpMenu3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenu3Layout.setVerticalGroup(
            jpMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenu3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtIconoAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(47, 47, 47)
                .addComponent(btnCrearuser3)
                .addGap(18, 18, 18)
                .addComponent(btnVerLibros3)
                .addGap(18, 18, 18)
                .addComponent(btnReposicionLibro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(txtSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Bienvenido: Aquí podras ver todos los libros registrados actualmente que ha añadido el bibliotecario:");

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        jLabel3.setText("Buscador:");

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/para pricipiantes.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpMenu3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReposicionLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReposicionLibro3ActionPerformed
        Direccionar.DirigirResposicionLibro(); // Mostramos la ventana
        this.dispose();// Cerramos la ventana
    }//GEN-LAST:event_btnReposicionLibro3ActionPerformed

    private void btnCrearuser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearuser3ActionPerformed
       Direccionar.DirigirCrearUser();// Mostamos la ventana
       this.dispose(); // Cerramos la ventana
    }//GEN-LAST:event_btnCrearuser3ActionPerformed

    private void btnVerLibros3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLibros3ActionPerformed
       Direccionar.DirigirVerInfoLibro();// Mostramos la ventana
       this.dispose();// Cerramos la ventana
    }//GEN-LAST:event_btnVerLibros3ActionPerformed

    private void txtSalida3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalida3MouseClicked
        RegresarLogion.RegresarLogin();// Regresamos al login
        this.dispose();// Cerramos la pantalla
    }//GEN-LAST:event_txtSalida3MouseClicked

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscar(txtBuscador.getText());
    }//GEN-LAST:event_txtBuscadorKeyReleased

    // Metodo para mostrar los datos de los libros
    public void MostrarDatos()
    {
        String [] titulos = {"ID Libro","Codigo","Titulo","Categoria","Autor","Cantidad","Fecha Ingreso" ,"Dias Prestamos" ,"Costo"};
        String [] registros = new  String[9];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        String SQL ="SELECT * FROM libro;";
        
        try {
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery(SQL); 
            // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Codigo");
             registros[2] = rs.getString("Titulo");
             registros[3] = rs.getString("Categoria");
             registros[4] = rs.getString("Autor");
             registros[5] = rs.getString("Cantidad");
             registros[6] = rs.getString("FechaIngreso");
             registros[7] = rs.getString("DiasPrestamos");
             registros[8] = rs.getString("Costo");
             modelo.addRow(registros);
            }
            tblLibros.setModel(modelo);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage()); // Muestrar el error al mostrar los datos 
        }
        
        
        
    }
    
    
    ////////////////////////////////////////////////////////////////////////////
    ////////                        Buscador                           //////// 
    ///////////////////////////////////////////////////////////////////////////
    
    // Metodo para buscar la palabra por medio del nombre que ingrese por el usario
    
    public void buscar(String valor)
    {
        String [] titulos = {"ID Libro","Codigo","Titulo","Categoria","Autor","Cantidad","Fecha Ingreso" ,"Dias Prestamos" ,"Costo"};
        String [] registros = new  String[9];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        //Realizamos la consulta para mostrar los datos
        String SQL ="SELECT * FROM libro where Titulo like '%"+valor+"%' or Categoria like '%"+valor+"%' or Codigo like '%"+valor+"%' ";
        
        try
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
             // Reccoremos la tabla para traer dicha información de cada empleado
            while(rs.next())
            {
             registros[0] = rs.getString("IDlibro");
             registros[1] = rs.getString("Codigo");
             registros[2] = rs.getString("Titulo");
             registros[3] = rs.getString("Categoria");
             registros[4] = rs.getString("Autor");
             registros[5] = rs.getString("Cantidad");
             registros[6] = rs.getString("FechaIngreso");
             registros[7] = rs.getString("DiasPrestamos");
             registros[8] = rs.getString("Costo");
             modelo.addRow(registros);
            }
            tblLibros.setModel(modelo);
            
            
            
        } catch (Exception e){
             JOptionPane.showMessageDialog(null, "Error al mostrar datos Busqueda" + e.getMessage());  
        }
        
    }
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVerLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVerLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVerLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVerLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVerLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrearuser3;
    public javax.swing.JButton btnReposicionLibro3;
    public javax.swing.JButton btnVerLibros3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMenu3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JLabel txtIconoAdmin3;
    public javax.swing.JLabel txtSalida3;
    // End of variables declaration//GEN-END:variables
}
